### ISSUE TITLE
Package self-tests into Monocypher itself

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#14] opened 2017-08-07 03:53 UTC
The README reads:

> *Do not* use Monocypher without running the self contained tests at least once.

Which is solid advice. However, I'm concerned about the scenario where you're the developer of an application unable to control where your code is actually going to run (e.g. you have some code, someone runs it on MIPS64 and Monocypher starts breaking; however, the user only sees that the application "doesn't work" because the crypto is broken).

Thoughts on including `tests/self.c` into Monocypher itself or at least a mention in the manual to `cat src/monocypher.c tests/self.c > amalgamation.c` and renaming `main()`? It has to be optional and not called automatically in case of things like embedded platforms, where developers can check the platform itself but running all the tests would be (1) rather time consuming, or (2) impossible with its stack size.

**Comment by LoupVaillant** [comment] 2017-08-07 11:38
Hmm, that's tricky. First, the tests aren't as portable or as easy to deploy than Monocypher itself. Second, the self-consistency tests don't test Monocypher exactly as it was intended to be used: with Blake2b EdDSA. Instead, it only tests Ed25519, because that's what I found test vectors for at the time.

I think I'll still keep the code and the tests separate, but we should do a couple adjustments:

* `cat` the generated test vectors header into `self.c` directly, instead of `#include`ing them. That way we have a single test file that is easy to distribute and compile into whatever test suite.
* Rename `main()` as you suggested.
* Have the tests run with Blake2b EdDSA by default, and provide a `-DED25519_SHA512` switch if the user wants Ed25519. That way the use tests the real thing in all cases.

Additionally, I think we should make test vectors out of most comparison tests. The idea is to make the self-consistency tests sufficient. Users should be able to compare Monocypher to other implementations, but they shouldn't *have* to.

I have other issues as well. The repository has become kind of a mess over time, with too many files and scripts to contend with. I think the toplevel directory should contain only those:

- `test.sh` would perform all the tests (with options such as `self` alone, Valgrind, Clang sanitisers, coverage…)
- `distribute.sh` would package the source, self-consistency tests, and manual, in a little self-contained directory, which can then be compressed and distributed for each release. The full test suite would only be accessible from the GitHub repository, but that won't be a problem if we make sure the self-consistency tests are enough.

**Comment by LoupVaillant** [comment] 2017-09-20 22:28
The test suite has now zero dependency. (Provided you have `vectors.h`, which will be provided to end users.)

Running those tests however takes a noticeable amount of time, and the binary weights 1.3 _megabytes_ (`vectors.h` is huge).

Because of this, I recommend we run those tests once per target platform, or as part as the application's unit tests. This is easily done: end users only need `utils.h`, `utils.c`, and `test.c`, and if they're lazy they can just call `make test`.

Maybe some users will still want startup-time tests, citing the likes of Libsodium. But Libsodium does this to select potentially non-portable implementations like hand crafted vectorised assembly, so it can revert back to portable C if they don't work. Monocypher uses portable C/C++ to begin with, it doesn't need this.

I'm closing this. If someone thinks I missed something, please re-open it.

**Closed by LoupVaillant** 2017-09-20 22:28 UTC
