### ISSUE TITLE
Building produces many switch/case fallthrough many warnings

### ISSUE THREAD

**Issue by rain-1** [LoupVaillant/Monocypher#5] opened 2017-08-03 11:22 UTC
When compiling the tests there are so many warnings it is hard to see what's happening. Based on [Warning Options](https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/Warning-Options.html#index-Wimplicit-fallthrough) why not either:

* add `-Wimplicit-fallthrough=0`
* add `-Wimplicit-fallthrough=3` plus `/* FALLTHRU */` comments.

**Comment by Rukachan** [comment] 2017-08-03 11:40
If it is hard to see what's happening just disable the warnings concerning switches.

**Comment by rain-1** [comment] 2017-08-03 14:36
that's what I'm suggesting.

**Comment by CuleX** [comment] 2017-08-04 06:43
On OpenBSD 6.1, which is the latest OpenBSD right now:

    $ gcc -Wimplicit-fallthrough=3 -o x x.c
    cc1: error: unrecognized command line option "-Wimplicit-fallthrough=3
    $ ls x
    ls: x: No such file or directory
    $ gcc --version
    gcc (GCC) 4.2.1 20070719

This is an example; compilers can and will abort on unknown options. Even if repository is just meant for running the tests, it seems Monocypher tries hard to stay portable. I just felt I should point that out.

However, given this repository is basically just for running the tests, and production deployments *may* invoke `-Wimplicit-fallthrough=3`, adding `/* FALLTHRU */` or one of its variants certainly won't hurt.

**Comment by LoupVaillant** [comment] 2017-08-05 23:16
Indeed, I'd like to keep it portable. This would rule out the compilation option.

I don't have those warnings in my platform, so I wonder what is happening. rain-1, I have 2 questions:

1. Could you show us a dump from a  `make donna` build, and tell us about your platform and compiler version?

2. Does merely adding a /* FALLTHRU */ comment, without modifying the makefile works? I would certainly accept a patch that only adds this comment.

**Comment by rain-1** [comment] 2017-08-06 09:39
I have `gcc version 7.1.1 20170630 (GCC)`.

here is the output of `make 2> dump.txt`:

```
In file included from tests/ed25519-donna/ed25519-donna.h:58:0,
                 from tests/ed25519-donna/ed25519.c:17:
tests/ed25519-donna/modm-donna-32bit.h: In function ‘lt256_modm_batch’:
tests/ed25519-donna/modm-donna-32bit.h:405:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 8: if (a[8] > b[8]) return 0; if (a[8] < b[8]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:406:3: note: here
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:406:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:407:3: note: here
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:407:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:408:3: note: here
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:408:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:409:3: note: here
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:409:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:410:3: note: here
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:410:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:411:3: note: here
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:411:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:412:3: note: here
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:412:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:413:3: note: here
   case 0: if (a[0] > b[0]) return 0; if (a[0] < b[0]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h: In function ‘sub256_modm_batch’:
tests/ed25519-donna/modm-donna-32bit.h:387:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 8: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:388:3: note: here
   case 7: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:388:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 7: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:389:3: note: here
   case 6: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:389:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 6: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:390:3: note: here
   case 5: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:390:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 5: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:391:3: note: here
   case 4: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:391:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 4: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:392:3: note: here
   case 3: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:392:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 3: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:393:3: note: here
   case 2: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:393:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 2: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:394:3: note: here
   case 1: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:394:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 1: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:395:3: note: here
   case 0:
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h: In function ‘lte256_modm_batch’:
tests/ed25519-donna/modm-donna-32bit.h:422:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 8: if (a[8] > b[8]) return 0; if (a[8] < b[8]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:423:3: note: here
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:423:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:424:3: note: here
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:424:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:425:3: note: here
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:425:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:426:3: note: here
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:426:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:427:3: note: here
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:427:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:428:3: note: here
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:428:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:429:3: note: here
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:429:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:430:3: note: here
   case 0: if (a[0] > b[0]) return 0; if (a[0] < b[0]) return 1;
   ^~~~
```

`/* FALLTHRU */` alone does not make the warnings go away.

**Comment by rain-1** [comment] 2017-08-06 09:44
https://github.com/LoupVaillant/Monocypher/pull/12

**Comment by CuleX** [comment] 2017-08-06 09:54
This seems to be a [gcc 7 feature](https://gcc.gnu.org/gcc-7/changes.html). I could reproduce the issue on Fedora 26, shipping gcc 7.1.1. `-Wextra` pulls in `-Wimplicit-fallthrough`.

Interestingly, the [gcc 7 documentation](https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/Warning-Options.html#index-Wimplicit-fallthrough) says:

> The `-Wimplicit-fallthrough=3` warning is enabled by `-Wextra`.

However, this mismatches the observed behavior. This might be worth pursuing upstream.

**Comment by rain-1** [comment] 2017-08-06 11:15
Thank you for looking into it further, nice find.

**Comment by LoupVaillant** [comment] 2017-08-06 12:05
CuleX, I'm not sure I understand your comment. Are you saying pull request #12 isn't enough of Fedora 26, gcc 7.1.1?

**Comment by CuleX** [comment] 2017-08-06 13:42
@LoupVaillant, yes, that's what I'm saying. On Fedora 26, gcc 7.1.1 (from repositories), building with pull request #12 yields this output. I've added git information to make sure which commit we're talking about.

```
[user@host Monocypher]$ git pull
Already up-to-date.
[user@host Monocypher]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
[user@host Monocypher]$ git log --pretty=oneline|head -n 2
3e7f6ad7f03498c4ee83a3de5e169e98c8ba9980 Merge pull request #12 from rain-1/master
012143cb0878398d9c8bb94c779e8f44f1ea6d8a add /* FALLTHRU */ comments to silence warnings
[user@host Monocypher]$ make donna
gcc -std=gnu99  -I src -pedantic -Wall -Wextra -O3 -march=native -o bin/classic_monocypher.o -c src/monocypher.c
gcc -std=gnu99  -I src -pedantic -Wall -Wextra -O3 -march=native -o bin/donna.o -c tests/ed25519-donna/ed25519.c -DED25519_CUSTOMHASH -DED25519_TEST -DED25519_NO_INLINE_ASM -DED25519_FORCE_32BIT
In file included from tests/ed25519-donna/ed25519-donna.h:58:0,
                 from tests/ed25519-donna/ed25519.c:17:
tests/ed25519-donna/modm-donna-32bit.h: In function ‘lt256_modm_batch’:
tests/ed25519-donna/modm-donna-32bit.h:405:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 8: if (a[8] > b[8]) return 0; if (a[8] < b[8]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:406:3: note: here
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:406:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:407:3: note: here
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:407:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:408:3: note: here
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:408:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:409:3: note: here
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:409:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:410:3: note: here
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:410:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:411:3: note: here
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:411:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:412:3: note: here
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:412:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:413:3: note: here
   case 0: if (a[0] > b[0]) return 0; if (a[0] < b[0]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h: In function ‘sub256_modm_batch’:
tests/ed25519-donna/modm-donna-32bit.h:387:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 8: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:388:3: note: here
   case 7: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:388:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 7: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:389:3: note: here
   case 6: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:389:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 6: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:390:3: note: here
   case 5: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:390:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 5: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:391:3: note: here
   case 4: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:391:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 4: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:392:3: note: here
   case 3: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:392:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 3: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:393:3: note: here
   case 2: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:393:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 2: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:394:3: note: here
   case 1: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:394:90: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 1: out[i] = (a[i] - b[i]) - carry; carry = (out[i] >> 31); out[i] &= 0x3fffffff; i++;
                                                                                         ~^~
tests/ed25519-donna/modm-donna-32bit.h:395:3: note: here
   case 0:
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h: In function ‘lte256_modm_batch’:
tests/ed25519-donna/modm-donna-32bit.h:422:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 8: if (a[8] > b[8]) return 0; if (a[8] < b[8]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:423:3: note: here
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:423:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 7: if (a[7] > b[7]) return 0; if (a[7] < b[7]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:424:3: note: here
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:424:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 6: if (a[6] > b[6]) return 0; if (a[6] < b[6]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:425:3: note: here
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:425:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 5: if (a[5] > b[5]) return 0; if (a[5] < b[5]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:426:3: note: here
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:426:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 4: if (a[4] > b[4]) return 0; if (a[4] < b[4]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:427:3: note: here
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:427:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 3: if (a[3] > b[3]) return 0; if (a[3] < b[3]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:428:3: note: here
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:428:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 2: if (a[2] > b[2]) return 0; if (a[2] < b[2]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:429:3: note: here
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
   ^~~~
tests/ed25519-donna/modm-donna-32bit.h:429:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
   case 1: if (a[1] > b[1]) return 0; if (a[1] < b[1]) return 1;
                                         ^
tests/ed25519-donna/modm-donna-32bit.h:430:3: note: here
   case 0: if (a[0] > b[0]) return 0; if (a[0] < b[0]) return 1;
   ^~~~
gcc -std=gnu99  -I src -pedantic -Wall -Wextra -O3 -march=native -o donna tests/donna.c bin/classic_monocypher.o bin/donna.o -I tests/ed25519-donna
[user@host Monocypher]$ 
```

**Comment by LoupVaillant** [comment] 2017-08-06 14:24
Well, we tried. I think we'd best drop this for now, and report the problem upstream.

I'm also tempted to disable warnings with the -w option, when compiling the ed25519-donna, but I'm not sure we can guarantee it will override -Wall and -Wextra.

**Comment by rain-1** [comment] 2017-08-06 14:51
What about just merging the patch that only adds the `/* FALLTHRU */` comments and closing this?

**Comment by CuleX** [comment] 2017-08-06 14:51
Adding `-w` like that silences the warnings, yes.

I'm a bit worried about doing so because it might drown out genuinely relevant warnings in case donna performs actions that actually break a platform, making the test fail even though Monocypher works, but I suppose the other tests suffice.

**Comment by LoupVaillant** [comment] 2017-08-06 15:22
Hmm, better be on the same side, and only silence the fallthrough warning. We'll silence other warnings as we go. So, that would be `-Wimplicit-fallthrough=3` instead of `-w`. I'll make the change and close the issue. I can't test it on my platform, I just pray I won't mess this up. :crossed_fingers:

**Comment by LoupVaillant** [comment] 2017-08-06 15:28
Arrgh, this doesn't compile! My "old" compiler (gcc 5.4.0) doesn't recognise the warning and refuses to compile!

Sorry, I can't fix this here, and I'm not sure even floodyberry himself can do much about it. That's a won't fix. :cry:

**Closed by LoupVaillant** 2017-08-06 15:28 UTC
